# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='types',
            old_name='country',
            new_name='name',
        ),
    ]
